// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCacRYuUKMjxNqytKMp5rF7nhwZzH2qmYU',
    appId: '1:831754256323:android:009ecff7db30875311c776',
    messagingSenderId: '831754256323',
    projectId: 'nightbite-37fa9',
    storageBucket: 'nightbite-37fa9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT7blsllStxwAO_fUhpXyFNac0uD-X7do',
    appId: '1:831754256323:ios:4c8d219ed149a8f511c776',
    messagingSenderId: '831754256323',
    projectId: 'nightbite-37fa9',
    storageBucket: 'nightbite-37fa9.appspot.com',
    androidClientId: '831754256323-qng079ovm0jfckc412mu0oc2i71428th.apps.googleusercontent.com',
    iosClientId: '831754256323-03l7sbv0nlep6rlheqrjc81vqib03tvf.apps.googleusercontent.com',
    iosBundleId: 'com.codeforany.foodDelivery',
  );
}
